version: "3.9"

services:

  mongodb:

    image: mongo:7

    container_name: mongodb

    restart: always

    ports:
      - "27017:27017"

    volumes:
      - mongodb-data:/data/db

    networks:
      - todo-network


  backend:

    build: ./backend

    container_name: backend

    restart: always

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    depends_on:
      - mongodb

    networks:
      - todo-network


  frontend:

    build: ./frontend

    container_name: frontend

    restart: always

    ports:
      - "3000:80"

    depends_on:
      - backend

    networks:
      - todo-network


volumes:

  mongodb-data:


networks:

  todo-network: